### ISSUE TITLE
Breaks shell command because of ; character

### ISSUE THREAD

**Issue by hyperknot** [jakubpawlowicz/clean-css-cli#12]
How is the official example of 

```
cleancss -O1 all:off;tidySelectors:on one.css
```

supposed to work? To all of my knowledge this is interpreted as two separate commands by bash. Of course neither `cleancss -O1 all:off` nor `tidySelectors:on one.css` is a valid command, so it returns a help for the first one and `-bash: tidySelectors:on: command not found` for the second one.

**Comment by jakubpawlowicz** [comment]
I think docs are wrong as it should be `cleancss -O1 "all:off;tidySelectors:on" one.css` - could you give this one a try?

**Comment by hyperknot** [comment]
Yes, with quotation marks it works well.

**Comment by jakubpawlowicz** [comment]
It's fixed then.
