### ISSUE TITLE
Can we clean multiples files using globs ?

### ISSUE THREAD

**Issue by francoismassart** [jakubpawlowicz/clean-css-cli#19]
If I have css files than I would like to clean like so:

```
css/
  style.css
  contact/
    contact.css
```

Can I use `clean-css-cli` like:

```
cleancss --level 1 --output css/**/*.min.css css/**/*.css
```

I do not want to list all my css in the command line or neither to edit the command line every time I add a new css file.

What I am aiming for is this result:

```
css/
  style.css
  style.min.css
  contact/
    contact.css
    contact.min.css
```

I could also accept having the source css file overwritten...

Thank you for your help.

**Comment by francoismassart** [comment]
I was able to do it thanks to a comment inside the issue #18 :

https://github.com/jakubpawlowicz/clean-css-cli/issues/18#issuecomment-372310146

This npm script will replace the files...
```
"css-minify-all": "foreach -g \"css/**/*.css\" -x \"cleancss --level 1 #{path} -o #{path}\" --no-c"
```

**Comment by jakubpawlowicz** [comment]
Please note it can be now done via `--batch` option in clean-css-cli v5: see https://github.com/jakubpawlowicz/clean-css-cli#how-to-process-multiple-files-without-concatenating-them-into-one-output-file
