### ISSUE TITLE
Allow * when specifying multiple input files

### ISSUE THREAD

**Issue by Cezille07** [jakubpawlowicz/clean-css-cli#2]
When listing input files as

    cleancss public/css/* public/app.css

it gives the error: 

    WARNING: Invalid character(s) '/*;@import public/app.css;' at 1:18. Ignoring.

Different variations of forward and backward slash, as well as removing the `*` (hoping it would peek into the folder), resulted in failure as well.

It would be handy if I didn't have to list each file separately, by allowing a wildcard `*`. I would like to merge the css files from imported libraries with my own css to reduce the number of http calls the browser has to make. Unfortunately, the calls to this tool become quite lengthy due to the number of libraries.

Version: 4.0.0
OS: Windows

**Comment by jakubpawlowicz** [comment]
Yup, we could have it in CLI. 👍

**Comment by jakubpawlowicz** [comment]
@Cezille07 you can do it now in clean-css 4.1, thanks for the idea!

**Comment by Cezille07** [comment]
Awesome, thanks! :D
