### ISSUE TITLE
Update clean-css version to latest

### ISSUE THREAD

**Issue by kgriffs** [jakubpawlowicz/clean-css-cli#22]
Hi, I just noticed that `clean-css` is set to version `4.1.9` in the dependencies. Is there any way we could get a new CLI release with that dep version bumped up?

**Comment by jakubpawlowicz** [comment]
I am aware I failed to update `clean-css-cli` at couple times when `clean-css` version was bumped - I think it was with the latter 4.1.10, 4.1.11, and 4.2.3 versions. Sorry about that! I do my best to follow them closely in 5.x or do you think there's still a need to release those pinned old versions?
