### ISSUE TITLE
Cannot install in docker container

### ISSUE THREAD

**Issue by benmackerras** [jakubpawlowicz/clean-css-cli#24]
I have a simple Dockerfile:
 FROM node:latest
 RUN npm install -g handlebars uglify-es less clean-css-cli

When i build the image everything seems to run fine:

Step 2/2 : RUN npm install -g handlebars uglify-es less clean-css-cli
 ---> Running in 21f8aba5497b
/usr/local/bin/cleancss -> /usr/local/lib/node_modules/clean-css-cli/bin/cleancss
/usr/local/bin/handlebars -> /usr/local/lib/node_modules/handlebars/bin/handlebars
/usr/local/bin/lessc -> /usr/local/lib/node_modules/less/bin/lessc
/usr/local/bin/uglifyjs -> /usr/local/lib/node_modules/uglify-es/bin/uglifyjs

However when i run the container cleancss is missing from both /usr/local/bin and /usr/local/lib/node_modules
All other modules install fine
Am i missing something about installing clean-css-cli?

Node version: 10.7.0
Npm version: 6.1.0
Docker version: 17.09.0-ce, build afdb6d4

**Comment by jakubpawlowicz** [comment]
Hmmm, I had a local docker image running just fine, so it should work fine.

Is there even a `/usr/local/lib/node_modules/clean-css-cli` in there?

**Comment by benmackerras** [comment]
No, the clean-css-cli folder is missing completely

**Comment by jakubpawlowicz** [comment]
What's then the content of your `/usr/local/lib/node_modules`? What if you ran the container and executed `npm install -g clean-css-cli` manually?

I see no reason why it may not work.

**Comment by benmackerras** [comment]
Contents of /usr/local/lib/node_modules is handlebars npm uglify-es less
Running `npm install -g clean-css-cli` manually inside the container installs fine

**Comment by jakubpawlowicz** [comment]
That's odd. What if you put `npm install -g clean-css-cli` as a separate entry in your Dockerfile?

**Comment by jakubpawlowicz** [comment]
Please reopen if needed.
