### ISSUE TITLE
Provide inputSourceMap

### ISSUE THREAD

**Issue by mistic100** [jakubpawlowicz/clean-css-cli#27]
There does not seem to be a way to provide an input sourcemap when using the CLI.
Please add a `--input-source-map` option or allow `--source-map` to accepts a path to an existing map.

**Comment by rbaras** [comment]
+1

**Comment by ionutvmi** [comment]
@jakubpawlowicz do you accept PRs for this feature ?

**Comment by jakubpawlowicz** [comment]
@ionutvmi sure, go for it!

**Comment by jakubpawlowicz** [comment]
Fixed in #32.
