### ISSUE TITLE
How do we preserve ALL comments?

### ISSUE THREAD

**Issue by IAMtheIAM** [jakubpawlowicz/clean-css-cli#30]
I tried changing specialComments to `0`, `1`, and `all` and it had no effect. It kept the special comments. 

How do we tell it to keep all comments?

**Comment by nolanwrightdev** [comment]
I found the README misleading on this point. I got it working with `cleancss -O1 'all:on;specialComments:0' [...]`. So the optimization flags are not mutually exclusive. Even if you want level 2 optimizations, you need to set `specialComments` with the `-O1` option.

**Comment by l2aelba** [comment]
Yes how to do that?

**Comment by jakubpawlowicz** [comment]
@l2aelba - I've updated docs to make it clear what character needs to prefix optimizations level.
