### ISSUE TITLE
skipProperties - what is the proper usage?

### ISSUE THREAD

**Issue by IAMtheIAM** [jakubpawlowicz/clean-css-cli#31]
Hi, `skipProperties` says it takes a list but there is no example and I couldn't find this anywhere in the cli code. How do we use this option on the CLI? Thanks!

**Comment by jakubpawlowicz** [comment]
The way is:

```sh
cleancss -O2 skipProperties:list-style,transition path/to/input.css
```

All properties come as comma separated list.
