### ISSUE TITLE
npm update -g clean-css-cli does not update the clean-css dependency to the latest version

### ISSUE THREAD

**Issue by tssajo** [jakubpawlowicz/clean-css-cli#4]
You fixed a bug in `clean-css 4.0.4` and suggested to try that.

I already had clean-css-cli installed globally, I previously used this command to install clean-css-cli:
`npm install -g clean-css-cli`
and it properly installed (at that time) `clean-css 4.0.2` as clean-css-cli's own dependency.

Now that you released `clean-css 4.0.4`, I tried to update `clean-css-cli` like this:

`npm update -g clean-css-cli`
but this command did nothing, clean-css-cli did NOT update its dependency from `clean-css 4.0.2` to `clean-css 4.0.4` as a normal user would expect.

The only way I found to update `clean-css-cli` to a version which uses the new `clean-css 4.0.4` was this:
`npm uninstall -g clean-css-cli`
followed by:
`npm install -g clean-css-cli`

This is not too ideal... In other words: it's hard to update `clean-css-cli`, unless every time when you release a new version of `clean-css` you cut a release of `clean-css-cli` as well. And update clean-css-cli's package.json file, this part:
```
"dependencies": {
    "clean-css": "4.x",
```
to something like:
```
"dependencies": {
    "clean-css": "4.0.4",
```
If you did this then `npm update -g clean-css-cli` would have worked ...

**Comment by jakubpawlowicz** [comment]
Sorry @tssajo that it didn't work out of the box but having CLI as a separate package is new to me - following some investigation ^ I decided to bump CLI when API is.

**Comment by tssajo** [comment]
@jakubpawlowicz Thanks!

This is perfect: `I decided to bump CLI when API is`

**Comment by jakubpawlowicz** [comment]
👍 I'm publishing all missing CLI releases as we speak.

**Comment by jakubpawlowicz** [comment]
Everything up to 4.0.5 is out.

**Comment by tssajo** [comment]
`npm update -g clean-css-cli` worked perfectly this time. Thanks, again!

**Comment by phiw13** [comment]
@jakubpawlowicz 
Updating is now smooth and easy. Thank you.

**Comment by jakubpawlowicz** [comment]
👍
