### ISSUE TITLE
Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by iJKTen** [jakubpawlowicz/clean-css-cli#41]
I did an npm install clean-css-cli

In my webpack.config.js file imported the module
const CleanCSS = require('clean-css-cli');

Using webpack-merge-and-include-globally to merge multiple CSS files and my config looks like

```
const path = require('path');
const MergeIntoSingle = require('webpack-merge-and-include-globally');
const CleanCSS = require('clean-css-cli');

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  plugins: [
    new MergeIntoSingle({
      files: [{
        src: ['src/style.css', 'src/style2.css'],
        dest: 'bundle.css',
     
        // also possible:
        //
        dest: code => ({
          'bundle.css':new CleanCSS({}).minify(code)
        }),
      }]
    })
  ]
};
```

On npx webpack I get an error that says
TypeError: Cannot read property '1' of undefined
    at Command.parse (/Users/jaikirdatt/development/blog/webpack-test/node_modules/commander/index.js:462:43)
    at new cli (/Users//development/blog/webpack-test/node_modules/clean-css-cli/index.js:120:12)
    at Object.dest (/Users/jaikirdatt/development/blog/webpack-test/webpack.config.js:20:24)
    at /Users/jaikirdatt/development/blog/webpack-test/node_modules/webpack-merge-and-include-globally/index.node6-compatible.js:97:50
    at Generator.next (<anonymous>)
    at step (/Users//development/blog/webpack-test/node_modules/webpack-merge-and-include-globally/index.node6-compatible.js:3:191)
    at /Users//development/blog/webpack-test/node_modules/webpack-merge-and-include-globally/index.node6-compatible.js:3:361

**Comment by jakubpawlowicz** [comment]
I think what you really want here is to require `clean-css` not `clean-css-cli` in line 3, i.e.

```js
const CleanCSS = require('clean-css');
```

I see no reason why would you want to minify your code through CLI when it can be ran via standard module interface, but please reopen this issue if I'm wrong.
