### ISSUE TITLE
Batch mode exclude files

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css-cli#51]
@jakubpawlowicz I'm experimenting with the `--batch` option which seems exactly what we need on Bootstrap.

The problem I have is that I'm not sure how to exclude files. Currently we have all of our CSS files in one dir:

```
bootstrap-grid.css
bootstrap-grid.min.css
bootstrap-grid.rtl.css
bootstrap-grid.rtl.min.css
bootstrap-reboot.css
bootstrap-reboot.min.css
bootstrap-reboot.rtl.css
bootstrap-reboot.rtl.min.css
bootstrap-utilities.css
bootstrap-utilities.min.css
bootstrap-utilities.rtl.css
bootstrap-utilities.rtl.min.css
bootstrap.css
bootstrap.min.css
bootstrap.rtl.css
bootstrap.rtl.min.css
```

I tried excluding the files that end with `*.min.css` but it doesn't work:

```shell
cleancss -O1 --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/ --batch --batch-suffix ".min" "dist/css/*.css" "!dist/css/*.min.css"
WARNING: Invalid character(s) '/*.min.css);' at 1:21. Ignoring.
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, open '!dist/css/*.min.min.css'
```

Am I maybe missing something?

Thanks!

**Comment by jakubpawlowicz** [comment]
Hey @XhmikosR - I thought it's possible but really haven't tested for it until you asked. Looks like a small change will be needed as `glob` expects excluding pattern to be passed via `ignore` option. Let me add it tomorrow.

**Comment by XhmikosR** [comment]
Thanks @jakubpawlowicz. BTW the failure didn't result in an error code 1 so the build (wrongfully?) continues on linux. On my Windows VM, the build does fail with 1.

**Comment by XhmikosR** [comment]
This is from Linux https://github.com/twbs/bootstrap/runs/1871881620#step:6:47

**Comment by jakubpawlowicz** [comment]
Since CLI returns just a warning then the build continues on Linux just fine. It's interesting the build does return error code 1 on Windows though.

**Comment by jakubpawlowicz** [comment]
Re fix to this issue - please see the commit above. Can you possibly test it locally?

**Comment by XhmikosR** [comment]
@jakubpawlowicz confirmed it works now, thanks!
