### ISSUE TITLE
--skip-rebase should be the default

### ISSUE THREAD

**Issue by hyperknot** [jakubpawlowicz/clean-css-cli#6]
I want to provide a small, but important feedback, as it bit me really hard and I believe it'll bite many other users.

First and foremost, I am using clean-css and now the new clean-css-cli for CSS minification. This is the reference tool for this job, and congratulation for making this huge achievement!

However, the default URL rebasing is an extremely bug prone feature. Running the tool with one path in development (where rebasing might not trigger) might produce a totally different result compared to running in from a different path, or when bundling files for production in a script, because of the "smart" auto rebasing option.

I recommend switching that option off by default (as in making `--skip-rebase` the default) as it'll bite many other users who just prefer to use this tool as a CSS minifier, without any of the path relative smart rebasing magic (personally I'd categorise that feature as -O2 or even -O3).

**Comment by jakubpawlowicz** [comment]
Interesting idea. Given 4.0 switched to safer `-O1` optimization level it may be a good idea for rebasing to follow.

May I know whether you entirely disabled rebasing and if so how do you handle it when bundling assets?

**Comment by hyperknot** [comment]
I am using a custom build script where clean-css-cli is just an optimal minimization step. 
For including external stylesheets, I'm also using sass imports via node-sass.

**Comment by jakubpawlowicz** [comment]
Got it - since it'd be a breaking change it needs to wait until the next major release.

**Comment by hyperknot** [comment]
Sure, no problem, I've finally found the right switch and if people run
into the same problem they might find this issue by Google.

**Comment by jakubpawlowicz** [comment]
And rebasing will be off by default in clean-css-cli v5 due soon.
