### ISSUE TITLE
incorrect removal of % unit in linear-gradient()

### ISSUE THREAD

**Issue by phiw13** [jakubpawlowicz/clean-css-cli#62]
given: `cleancss -d -O2 --format 'breaks:afterComment=on' -o style.min.css style.css`

source:

```
background: linear-gradient(hsla(0, 0%, 98%, .8),hsla(0, 0%, 98%, .8)) 0 0 / 100% 1px no-repeat hsl(48, 75%, 77%);
```

result:

```
background: linear-gradient(hsla(0,0,98%,.8),hsla(0,0,98%,.8)) 0 0/100% 1px no-repeat #f0de98;
```

expected:

```
background: linear-gradient(hsla(0,0%,98%,.8),hsla(0,0%,98%,.8)) 0 0/100% 1px no-repeat #f0de98;
```

The `hsla` color notation **requires** the `%` unit for the second `0`.

cleancss 5.1 (and 5.0.1 before)
npm 7.5.4
node 14.15.4
macOS 11.2.1

cleancss-cli 4.3 handled it correctly

**Comment by jakubpawlowicz** [comment]
Hey @phiw13 - I'll check thoroughly tomorrow but please use `replaceZeroUnits: false` for the time being: https://github.com/jakubpawlowicz/clean-css#level-1-optimizations

Sorry for incovenience!

**Comment by phiw13** [comment]
OK, will try that later.

The funny-not-so-funny thing is: only `linear-gradient()` seems affected.

**Comment by jakubpawlowicz** [comment]
It's fixed in clean-css 5.2.0 out now on npm.

**Comment by phiw13** [comment]
clean-css 5.2.0 fixes this issue, thank you.

BTW, `replaceZeroUnits: false` did absolutely nothing.

**Comment by jakubpawlowicz** [comment]
:+1: 

Sorry about the suggestion then, I didn't test it at the time.
