### ISSUE TITLE
Batch suffix error under Windows 10

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css-cli#66]
Reported by @jasonreiche in #65 

> When I run the command above currently under Windows 10 PS, using double or single quotes, I get this error:
> 
>    error: option '--batch-suffix ' argument missing
>
> Running it without --batch-suffix results in files being created in place under source/

**Comment by jakubpawlowicz** [comment]
I tested this on Windows 10 with Node.js 14 and empty double quotes work for me, i.e.

```shell
cleancss --batch --batch-suffix "" path/to/css/file
```

correctly replaces CSS files in place.

Using a pair of single quotes, e.g `--batch-suffix ''` causes cleancss to treat that pair of single quotes as a suffix resulting in files like `reset''.css`. 

I'm going to add that info to Readme. 

Please retest if possible and let me know if this has to be reopened.

**Comment by ohaeusler** [comment]
I'll add something about this:

For me, this occurred even using double quotes. Using `--batch-suffix '""'` was the solution for me.
