### ISSUE TITLE
How to remove the injected sourceMappingURL?

### ISSUE THREAD

**Issue by andreasvirkus** [jakubpawlowicz/clean-css-cli#9]
Sorry, but I couldn't find an option to remove the inlined sourceMappingURL.

Currently it's longer than my actual CSS content and creates unnecessary bloat to the file (more than doubling the size: 9kB -> 23kB).

edit: an example of the file 
https://gist.github.com/andreasvirkus/15c7c2c3afcd6f69579890daeca2fe01

**Comment by ESPNMichaelKidd** [comment]
the inlined sourcemap seems to occur when using stdout, and not when specifying an output file

**Comment by ESPNMichaelKidd** [comment]
@andreasvirkus any chance your passing the output to postcss and not using the `--no-map` option?  That's what eventually fixed this for me

**Comment by jakubpawlowicz** [comment]
@andreasvirkus @ESPNMichaelKidd there are `--source-map` and `--source-map-inline-sources` options in CLI but both are disabled unless given.

**Comment by andreasvirkus** [comment]
@ESPNMichaelKidd Hmm...  I am passing the output to postcss for autoprefixes. I'll try the `--no-map` out tonight, thanks for the idea!

**Comment by andreasvirkus** [comment]
Yup. Running PostCSS with `--no-map` helped. Sorry for troubling. I didn't think to consider `postcss` as the culprit here.

**Comment by jakubpawlowicz** [comment]
It's weird you opened this issue in clean-css repo (not related to PostCSS) but glad you solved the problem! 👍
